=== FullService/xmlresume/trunk/resume/src/www/dtd/resume.dtd
<!--
resume.dtd - Resume Document Type Definition for XML

Copyright (c) 2000-2002 Sean Kelly
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the
   distribution.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

The doctype with FPI for this DTD is:

  <!DOCTYPE resume PUBLIC "-//Sean Kelly//DTD Resume @VERSION_DOTS@//EN"
                   "http://xmlresume.sourceforge.net/dtd/resume.dtd">

$Id$
-->

<!-- Grab a bunch of additional Latin characters courtesy of Norman -->
<!-- Walsh's extraction of the ISO 8879 set for DocBook XML. -->
<!ENTITY % ISOlat1.module "INCLUDE">
<![%ISOlat1.module;[
<!ENTITY % ISOlat1 PUBLIC
"ISO 8879:1986//ENTITIES Added Latin 1//EN//XML"
"iso-lat1.ent">
%ISOlat1;
<!--end of ISOlat1.module-->]]>

<!-- Inline elements -->
<!ENTITY % inlines "#PCDATA | emphasis | citation | url | link">

<!-- Sections of a resume -->
<!ENTITY % sections "(objective|history|academics|skillareas|skillarea|pubs|misc|referees|keywords|memberships|interests|awards)">

<!-- A collection of resumes -->
<!ELEMENT resumes (resume*)>
<!ATTLIST resumes id ID #IMPLIED
	xmlns     CDATA #FIXED "http://xmlresume.sourceforge.net/resume/0.0"
	xmlns:xsi CDATA #FIXED "http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation CDATA #IMPLIED>

<!-- A resume -->
<!ELEMENT resume (docpath?, header?, (%sections;)*, lastModified?, copyright?)>
<!ATTLIST resume id ID #IMPLIED
	xmlns     CDATA #FIXED "http://xmlresume.sourceforge.net/resume/0.0"
	xmlns:xsi CDATA #FIXED "http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation CDATA #IMPLIED>

<!-- A resume may be part of a hierarchy of documents with a single -->
<!-- root.  This docpath element specifies that hierarchy, plus the -->
<!-- URIs to the documents. -->
<!-- The following elements were deprecated as of 1.4.0. They will be removed
in a future version. -->
<!ELEMENT docpath (head?, node*, tail)>
<!ELEMENT head (label, uri)>
<!ELEMENT node (label, uri)>
<!ELEMENT tail (#PCDATA)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT uri (#PCDATA)>

<!-- The header of the resume contains your name and address. -->
<!ELEMENT header (name, address?, birth?, contact?)>
<!ELEMENT name (firstname, middlenames?, surname, suffix?)>
<!ATTLIST name id ID #IMPLIED>
<!ELEMENT firstname (#PCDATA)>
<!-- Use for one or more middle names or initials. -->
<!ELEMENT middlenames (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!-- suffix is intended for Jr., Sr., III, etc. -->
<!ELEMENT suffix (#PCDATA)>
<!ELEMENT birth (date)>

<!-- Your address is free-form text formatted as is proper for your -->
<!-- mailing standards.  To insert a line break, simply put a newline -->
<!-- in your document.  Mark up any other postal items with the element -->
<!-- from addrElements. -->
<!ENTITY % addrElements "street | street2 | suburb | ward | city | state | province | county | prefecture | zip | postalCode | country">
<!ELEMENT address (#PCDATA | %addrElements; | break)*>
<!ATTLIST address
    format (standard|european|italian) #IMPLIED
    id ID #IMPLIED>
<!ELEMENT street (#PCDATA)>
<!ATTLIST street id ID #IMPLIED>
<!-- Deprecated as of 1.3.3. Use multiple <street>s instead. -->
<!ELEMENT street2 (#PCDATA)>
<!ATTLIST street2 id ID #IMPLIED>
<!ELEMENT suburb (#PCDATA)>
<!ATTLIST suburb id ID #IMPLIED>
<!ELEMENT ward (#PCDATA)>
<!ATTLIST ward id ID #IMPLIED>
<!ELEMENT city (#PCDATA)>
<!ATTLIST city id ID #IMPLIED>
<!ELEMENT state (#PCDATA)>
<!ATTLIST state id ID #IMPLIED>
<!ELEMENT province (#PCDATA)>
<!ATTLIST province id ID #IMPLIED>
<!ELEMENT county (#PCDATA)>
<!ATTLIST county id ID #IMPLIED>
<!ELEMENT prefecture (#PCDATA)>
<!ATTLIST prefecture id ID #IMPLIED>
<!ELEMENT zip (#PCDATA)>
<!ATTLIST zip id ID #IMPLIED>
<!ELEMENT postalCode (#PCDATA)>
<!ATTLIST postalCode id ID #IMPLIED>
<!ELEMENT country (#PCDATA)>
<!ATTLIST country id ID #IMPLIED>
<!ELEMENT break EMPTY> <!-- Deprecated. -->
<!ELEMENT contact (phone|fax|pager|email|url|instantMessage)*>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone location (home | work | mobile) #IMPLIED>
<!ELEMENT fax (#PCDATA)>
<!ATTLIST fax location (home | work) #IMPLIED>
<!ELEMENT pager (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT instantMessage (#PCDATA)>
<!ATTLIST instantMessage service CDATA #IMPLIED>
<!ELEMENT link (#PCDATA)>
<!ATTLIST link href CDATA #IMPLIED>

<!-- Your lifelong objective. -->
<!ELEMENT objective (para+)>
<!ATTLIST objective id ID #IMPLIED>

<!-- Your previous employment history. -->
<!ELEMENT history (job+)>
<!ELEMENT job (jobtitle, employer, period, description?, projects?, achievements?)>
<!ATTLIST job id ID #IMPLIED>
<!ELEMENT jobtitle (#PCDATA)>
<!ELEMENT employer (%inlines;)*>
<!ATTLIST employer id ID #IMPLIED>
<!ELEMENT period (from, to)>
<!ELEMENT from (date | present)>
<!ELEMENT to (date | present)>
<!ELEMENT description (para+)>
<!ELEMENT projects (project+)>
<!ELEMENT project (%inlines;)*>
<!ELEMENT achievements (achievement+)>
<!ELEMENT achievement (%inlines;)*>

<!-- What academics, if any, you might possess. -->
<!ELEMENT academics (degrees, note?)>
<!ELEMENT degrees (degree+)>
<!ELEMENT degree (level, major, (date|period)?, institution?, subjects?, annotation?)>
<!ATTLIST degree id ID #IMPLIED>
<!ELEMENT level (#PCDATA)>
<!ELEMENT major (#PCDATA)>
<!ELEMENT institution (#PCDATA)>
<!ATTLIST institution id ID #IMPLIED>
<!ELEMENT subjects (subject+)>
<!ELEMENT subject (title,result)>
<!ELEMENT result (#PCDATA)>
<!ELEMENT annotation (#PCDATA)>
<!ELEMENT note (para+)>

<!-- Special skills you'd like to highlight, each in its own area. -->
<!-- skillareas should be removed in a future version, after people have had a
chance to remove it from their resumes. It was deprecated in version 1.4.0. -->
<!ELEMENT skillareas (skillarea+)> <!-- Deprecated in 1.4.0 -->
<!ELEMENT skillarea (title, skillset+)>
<!ATTLIST skillarea id ID #IMPLIED>
<!ELEMENT skillset (title?, (skill+ | skills))>
<!ATTLIST skillset id ID #IMPLIED>
<!-- skills should be removed in a future version, after people have had a
chance to remove it from their resumes. It was deprecated in version 1.4.0. -->
<!ELEMENT skills (skill+)> <!-- Deprecated in 1.4.0 -->
<!ATTLIST skills id ID #IMPLIED>
<!ELEMENT skill (%inlines;)*>
<!ATTLIST skill
    id ID #IMPLIED
    level CDATA #IMPLIED>

<!-- Have you published anything? -->
<!ELEMENT pubs (pub+)>
<!ENTITY % pubElements "(artTitle|bookTitle|author|date|pubDate|publisher|pageNums|url)">
<!ELEMENT pub (para | %pubElements;)*>
<!ATTLIST pub id ID #IMPLIED>
<!ELEMENT artTitle (#PCDATA | link)*>
<!ELEMENT bookTitle (#PCDATA | link)*>
<!ELEMENT author (#PCDATA)>
<!ATTLIST author name IDREF #IMPLIED>
<!ELEMENT pubDate (month?, year)> <!-- Deprecated in 1.4.0. -->
<!ELEMENT publisher (#PCDATA | link | url)*>
<!ELEMENT pageNums (#PCDATA)>

<!-- Professional memberships. -->
<!ELEMENT memberships (title, membership+)>
<!ELEMENT membership (title?, organization?, period?, description?)>
<!ATTLIST membership id ID #IMPLIED>
<!ELEMENT organization (#PCDATA)>
<!ATTLIST organization id ID #IMPLIED>

<!-- Interests and/or hobbies. -->
<!ELEMENT interests (title?, interest+)>
<!ELEMENT interest (title, description?)>

<!-- Awards or other honors. -->
<!ELEMENT awards (title?, award+)>
<!ELEMENT award (title, organization?, date?, description?)>

<!-- Final remarks. -->
<!ELEMENT misc (para+)>

<!-- The date the resume was last modified -->
<!ELEMENT lastModified (date)>

<!-- A copyright on a resume?  Absolutely.  This helps prevents -->
<!-- particularly annoying headhunters from plastering your resume all -->
<!-- over the place, and also prevents you from being hired at a place -->
<!-- that would otherwise want you, but does not want to pay tribute -->
<!-- to the particularly annoying headhunter who plastered your resume -->
<!-- there after grabbing it off the net. -->
<!ELEMENT copyright (year, name?, legalnotice?)>
<!ELEMENT company (#PCDATA)> <!-- Deprecated. -->
<!ELEMENT legalnotice (para+)>

<!-- For database retrieval (and web page insertion), some keywords. -->
<!ELEMENT keywords (keyword+)>
<!ELEMENT keyword (#PCDATA)>

<!-- The referees of the resume names and addresses. -->
<!ELEMENT referees (referee+)>
<!ELEMENT referee (name, title?, organization?, address?, contact?)>

<!-- Miscellaneous elements part of larger constructs. -->
<!ELEMENT para (%inlines;)*>
<!ELEMENT emphasis (#PCDATA)>
<!ELEMENT citation (#PCDATA)>
<!ELEMENT date (((dayOfMonth)?, month)?, year)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT dayOfMonth (#PCDATA)>
<!ELEMENT present EMPTY>
<!ELEMENT title (#PCDATA)>

=== FullService/xmlresume/tags/release-1_3_1/resume/examples/addressing/norway.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
Sample Norwegian address.  Uses 'european' format. Correct formatting is:

  Henrik Ibsen
  POB 1181 Sentrum
  0107 Oslo
  Norway

$Id$
-->

<?xml-stylesheet href="html.xsl" type="text/xsl"?>
<!DOCTYPE resume PUBLIC "-//Sean Kelly//DTD Resume 1.2.2//EN" "http://xmlresume.sourceforge.net/dtd/resume.dtd">

<resume>
  <header>
    <name>
      <firstname>Henrik</firstname>
      <surname>Ibsen</surname>
    </name>
    <address>
      <street>POB 1181 Sentrum</street>
      <city>Oslo</city>
      <postalCode>0107</postalCode>
      <country>Norway</country>
    </address>
  </header>
</resume>

=== FullService/xmlresume/tags/release-1_3_1/resume/examples/addressing/usa.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
Sample USA address.  Uses 'standard' format. Correct formatting is:

  Stewart Evans
  PO Box 1273
  Santa Cruz, CA 95061
  USA

$Id$
-->

<?xml-stylesheet href="html.xsl" type="text/xsl"?>
<!DOCTYPE resume PUBLIC "-//Sean Kelly//DTD Resume 1.2.2//EN" "http://xmlresume.sourceforge.net/dtd/resume.dtd">

<resume>
  <header>
    <name>
      <firstname>Stewart</firstname>
      <surname>Evans</surname>
    </name>
    <address>
      <street>PO Box 1273</street>
      <city>Santa Cruz</city>
      <zip>95061</zip>
      <state>CA</state>
      <country>USA</country>
    </address>
  </header>
</resume>

=== FullService/xmlresume/tags/release-1_4_1/resume/examples/addressing/uk.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
Sample UK address.  Uses 'standard' format. Correct formatting is:

  A.J. Smith
  3 High Street
  Otterly
  Southampton, Hants SO31 4NG
  UK

  Note that county is no longer a required field for UK addresses, but 
  it is in fairly common usage.

$Id$
-->

<?xml-stylesheet href="html.xsl" type="text/xsl"?>
<!DOCTYPE resume PUBLIC "-//Sean Kelly//DTD Resume 1.2.2//EN" "http://xmlresume.sourceforge.net/dtd/resume.dtd">

<resume>
  <header>
    <name>
      <firstname>A.J.</firstname>
      <surname>Smith</surname>
    </name>
    <address>
      <street>3 High Street</street>
      <street2>Otterly</street2>
      <city>Southampton</city>
      <county>Hants</county>
      <postalCode>SO31 4NG</postalCode>
      <country>UK</country>
    </address>
  </header>
</resume>

=== FullService/xmlresume/branches/DEVEL-2_0/examples/addressing/italy.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
Sample Italian address.  Use 'italian' format. Correct formatting is:

  Giuseppe Verdi
  Via Garibaldi, 23
  123 456 Sorrento (NA)
  Italy

$Id$
-->

<?xml-stylesheet href="html.xsl" type="text/xsl"?>
<!DOCTYPE resume PUBLIC "-//Sean Kelly//DTD Resume 1.2.2//EN" "http://xmlresume.sourceforge.net/dtd/resume.dtd">

<resume>
  <header>
    <name>
      <firstname>Giuseppe</firstname>
      <surname>Verdi</surname>
    </name>
    <address>
      <street>Via Garibaldi, 23</street>
      <city>Sorrento</city>
      <postalCode>123 456</postalCode>
      <province>NA</province>
      <country>Italy</country>
    </address>
  </header>
</resume>

=== FullService/xmlresume/tags/release-1_4_1/resume/src/www/maxbenson_professional.xml
<?xml version="1.0"?>
<?xml-stylesheet href="./xsl/html_professional.xsl" type="text/xsl"?>
<!DOCTYPE resume PUBLIC "-//Sean Kelly//DTD Resume 1.3.1//EN"
                        "./dtd/resume.dtd">
<resume>
	<header>
		<!-- changed MS address2 to address-->
		<name>
			<firstname>Max</firstname>
			<surname>Benson</surname>
		</name>
		<address>
			<street>100 Anywhere Street</street>
			<city>Anywhere</city>
			<state>NY</state>
			<zip>10280</zip>
		</address>
		<!--changed MS address1 to contact -->
		<contact>
			<phone>212-222-2222</phone>
			<email>maxbenson@foobar.net</email>
			<url>http.www.maxbenson.net/resume.html</url>
		</contact>
	</header>
	<objective>
		<para>To enter into that activity of the soul wherein I exhibit excellence</para>
	</objective>
	<!--	deleted SectionTitle and made History, Academics, and so on -->
	<history>
		<job>
			<jobtitle>National Sales Manager</jobtitle>
			<employer>Arbor Shoe</employer>
			<period>
				<from>
					<date>
						<month/>
						<year>1990</year>
					</date>
				</from>
				<to>
					<date>
						<month/>
						<year>1994</year>
					</date>
				</to>
			</period>
			<!-- RK: Deleted location of employer.  XSL indicates some handling of job city and state, but DTD does not? I couldn't figure out how to make it pass validation -->
			<achievements>
				<achievement>Increased sales from $50 million to $100 million.</achievement>
				<achievement>Doubled sales per representative from $5 million to $10 million.</achievement>
				<achievement>Suggested new products that increased earnings by 23%</achievement>
			</achievements>
		</job>
		<job>
			<jobtitle>District Sales Manager</jobtitle>
			<employer>Ferguson and Bardwell</employer>
			<period>
				<from>
					<date>
						<month/>
						<year>1985</year>
					</date>
				</from>
				<to>
					<date>
						<month/>
						<year>1990</year>
					</date>
				</to>
			</period>
			<!-- Deleted location of employer, no tag? -->
			<achievements>
				<achievement>Increased regional sales from $25 million to $350 million.</achievement>
				<achievement>Managed 250 sales representatives in 10 Western states.</achievement>
				<achievement>Implemented training course for new recruits — speeding profitability.</achievement>
			</achievements>
		</job>
		<job>
			<jobtitle>Senior Sales Representative</jobtitle>
			<employer>Duffy Vineyards</employer>
			<period>
				<from>
					<date>
						<month/>
						<year>1980</year>
					</date>
				</from>
				<to>
					<date>
						<month/>
						<year>1984</year>
					</date>
				</to>
			</period>
			<!-- Deleted location of employer, no tag? -->
			<achievements>
				<achievement>Expanded sales team from 50 to 100 representatives.</achievement>
				<achievement>Tripled division revenues for each sales associate.</achievement>
				<achievement>Expanded sales to include mass-market accounts.</achievement>
			</achievements>
		</job>
		<job>
			<jobtitle>Senior Sales Representative</jobtitle>
			<employer>LitWare, Inc.</employer>
			<period>
				<from>
					<date>
						<month/>
						<year>1975</year>
					</date>
				</from>
				<to>
					<date>
						<month/>
						<year>1980</year>
					</date>
				</to>
			</period>
			<!-- Deleted location of employer, no tag? -->
			<achievements>
				<achievement>Expanded territorial sales by 400%.</achievement>
				<achievement>Received company’s highest sales award four years in a row.</achievement>
				<achievement>Developed Excellence in Sales training course.</achievement>
			</achievements>
		</job>
	</history>
	<academics>
		<degrees>
			<degree>
				<level>B.A.</level>
				<major>Business Administration and Computer Science.</major>
				<!-- didn't have right structure to do a from-to period for the education 
				<period>
			<from><date><month/><year>1971</year></date></from>
			<to><date><month/><year>1975</year></date></to>
				</period> -->
				<date>
					<month>May</month>
					<year>1975</year>
				</date>
				<institution>South Ridge State University</institution>
				<annotation>Graduated summa cum laude.</annotation>
			</degree>
		</degrees>
	</academics>
	<!-- Did not include, no corresponding tags 
	<SectionTitle>
		<p>Interests</p>
	</SectionTitle>
	<Institution>
		<p>SR Board of Directors, running, gardening, carpentry, computers.</p>
	</Institution>
	<Normal>
		<p></p>
	</Normal>
	<SectionTitle>
		<p>Tips</p>
	</SectionTitle>
	<Objective>
		<p>What the heck are tips?</p>
	</Objective>
	<Normal>
		<p></p>
		<p/>
	</Normal>
-->
</resume>

=== FullService/xmlresume/trunk/resume/examples/example2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resume PUBLIC "-//Sean Kelly//DTD Resume @VERSION_DOTS@//EN"
  "http://xmlresume.sourceforge.net/dtd/resume.dtd">

<!--
example2.xml

Another example resume using the XML Resume Library.

Copyright (c) 2001-2002 Sean Kelly.  All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the
   distribution.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

-->
<resume id="x9281cp35">

  <header>
    <name id="a.kernighan">
      <firstname>Alexis</firstname>
      <surname>Kernighan</surname>
    </name>
    <!-- This person is using the untagged style address (lives in Cuba). -->
    <address>Reina #35, apt. 4a, e/ Gervasio y Escobar
Cuidad de la Habana, CP 11900
CUBA
</address>
  </header>

  <objective>
    <para>To achieve my Master Chef certification and become
      <emphasis>executive chef</emphasis> at a fine restaurant in the
      Hawaiian islands.
    </para>
  </objective>

  <skillarea>
    <title>Cooking Skills</title>
    <skillset>
      <title>General Experience</title>
      <skill>Gastronomy</skill>
      <skill>Culinary math</skill>
      <skill>Nutrition</skill>
      <skill>Sanitation</skill>
      <skill>Culinary French</skill>
      <skill>Meat identification</skill>
      <skill>Wines</skill>
      <skill>Restaurant Law</skill>
      <skill><citation>Brodeger's Sanitation</citation> science background</skill>
    </skillset>
    <skillset>
      <title>Culinary Skills</title>
      <skill>Braise</skill>
      <skill>Saut&eacute;</skill>
      <skill>Fry</skill>
      <skill>Bake</skill>
      <skill>Stocks</skill>
      <skill>Reductions</skill>
      <skill>Sauces</skill>
    </skillset>
    <skillset>
      <title>Cuisines</title>
      <skill>Seafood</skill>
      <skill>American Regional</skill>
      <skill>Asian</skill>
      <skill>Charcuterie</skill>
      <skill>Garde Manger</skill>
      <skill>P&acirc;tisserie</skill>
      <skill>Modern French</skill>
    </skillset>
  </skillarea>

  <history>
    <job>
      <jobtitle>Sous Chef</jobtitle>
      <employer>The Four Seasons</employer>
      <period>
	<from>
	  <date>
	    <month>March</month>
	    <year>1997</year>
	  </date>
	</from>
	<to>
	  <present/>
	</to>
      </period>
      <projects>
	<project>Fall Menu</project>
	<project>Revamping of Grill Area</project>
      </projects>
      <achievements>
	<achievement>Developed <emphasis>13</emphasis> new menu items</achievement>
	<achievement>Prepared daily operations plan</achievement>
        <achievement>Streamlined procedures for fresh foods
	  procurement</achievement>
      </achievements>
    </job>
    <job>
      <jobtitle>Assistant Chef</jobtitle>
      <employer>Zolo</employer>
      <period>
	<from>
	  <date>
	    <month>April</month>
	    <year>1993</year>
	  </date>
	</from>
	<to>
	  <date>
	    <month>January</month>
	    <year>1997</year>
	  </date>
	</to>
      </period>
      <description>
	<para>Prepared standard daily mise en place, stocks, and
	  sauces.  Assembled cold plates and salads.
	</para>
      </description>
    </job>
  </history>

  <memberships>
    <title>Professional Societies</title>
    <membership>
      <organization>Association of Aluminum Utensils</organization>
    </membership>
    <membership>
      <title>Grand Poobah</title>
      <organization>Stonecutters</organization>
    </membership>
    <membership>
      <title>Senior Fellow</title>
      <organization>Society for Creative Cuisine</organization>
      <period><from><date><month>February</month><year>1993</year></date></from>
	<to><present/></to></period>
      <description>
	<para>As senior fellow, I was responsible for all recruiting
	  efforts of the organization.
	</para>
      </description>
    </membership>
  </memberships>

  <misc>
    <para>What can't be captured on a r&eacute;sum&eacute; is my sheer
      level of <emphasis>enthusiasm</emphasis> for not just cooking
      food, but dealing with people.  I'm told I make nearly every
      kitchen run more smoothly because I know how to manage and make
      people want to <emphasis>do their best</emphasis>.
    </para>
    <para>I'm listed in <citation>Who's Who in American
	Restaurants</citation> as well as <citation>La
	Rubach&ograve;n</citation>.
    </para>
  </misc>

  <academics>
    <degrees>
      <degree>
	<level>AA</level>
	<major>Culinary Arts</major>
	<date>
	  <month>May</month>
	  <year>1995</year>
	</date>
	<institution>Culinary Institute of America</institution>
        <subjects>
	  <subject>
	    <title>Stocks, broths, and soups</title>
	    <result>A</result>
	  </subject>
	  <subject>
	    <title>French and world sauces</title>
	    <result>A</result>
	  </subject>
	  <subject>
	    <title>French cuisine</title>
	    <result>B</result>
	  </subject>
	  <subject>
	    <title>World cuisine</title>
	    <result>A</result>
	  </subject>
	  <subject>
	    <title>Kitchen sanitation</title>
	    <result>A</result>
	  </subject>
	  <subject>
	    <title>Pastry</title>
	    <result>B</result>
	  </subject>
	  <subject>
	    <title>Culinary history</title>
	    <result>A</result>
	  </subject>
	  <subject>
	    <title>Hotel restaurant management</title>
	    <result>C</result>
	  </subject>
	</subjects>	  
      </degree>
    </degrees>
  </academics>

  <pubs>
    <pub>
      <artTitle>High speed reduction of wine based sauces</artTitle>
      <bookTitle>Journal of the Occidental Culinary Federation</bookTitle>
      <author name="a.kernighan"/>
      <author>Charles Bell</author>
      <author>Kassandra Kassis</author>
      <pageNums>132-136</pageNums>
      <pubDate>
	<month>February</month>
	<year>2000</year>
      </pubDate>
      <publisher>OCF, New York, New York</publisher>
    </pub>

    <pub>
      <author name="a.kernighan"/>
      <pubDate>
	<year>1998</year>
      </pubDate>
      <publisher>Deltoid Press, <url>http://www.deltoid.co/</url></publisher>
      <bookTitle>The Texas Ranger Chow Book</bookTitle>
    </pub>
	
  </pubs>

  <referees>
    <referee>
      <name>
	<firstname>Indiana</firstname>
	<surname>O'Brien</surname>
      </name>
      <contact>
	<phone>408.555.1296</phone>
      </contact>
    </referee>
    <referee>
      <name>
	<firstname>Web</firstname>
	<surname>Melgood</surname>
      </name>
      <address>
	<street>3090 Deltoid</street>
	<city>Santa Yorba</city>
	<state>CA</state>
	<zip>95022</zip>
	<country>USA</country>
      </address>
    </referee>
  </referees>

</resume>

=== FullService/xmlresume/branches/DEVEL-2_0/examples/addressing/ireland.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
Sample Ireland address.  Uses 'standard' format. Correct formatting is:

  William Clifton
  1 O'Leary Place
  Cobh, Co. Cork 
  Ireland

$Id$
-->

<?xml-stylesheet href="html.xsl" type="text/xsl"?>
<!DOCTYPE resume PUBLIC "-//Sean Kelly//DTD Resume 1.2.2//EN" "http://xmlresume.sourceforge.net/dtd/resume.dtd">

<resume>
  <header>
    <name>
      <firstname>William</firstname>
      <surname>Clifton</surname>
    </name>
    <address>
      <street>1 O'Leary Place</street>
      <city>Coby</city>
      <county>Co. Cork</county>
      <country>Ireland</country>
    </address>
  </header>
</resume>
